module.exports = {
    // Role 
    READ_ROLES: "READ_ROLES",
    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    READ_SINGLE_ROLE: "READ_SINGLE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",

    // User
    CREATE_USER_ADMIN: "CREATE_USER_ADMIN",
    // READ_SINGLE_USER: "READ_SINGLE_USER",
    // READ_USERS: "READ_USERS",
}
